"""Init commands: init-dirs."""
import shutil
from datetime import datetime
from pathlib import Path

from core.utils import (
    find_project_root, load_json, load_markdown, save_json, get_config,
    get_research_map, require_project_root,
)

# Re-export shared commands from project module
from cli.commands.project import cmd_setup, cmd_preflight


def cmd_init_dirs(args):
    root = require_project_root()

    config = get_config(root)
    research_map = get_research_map(root, config)
    intake = load_markdown(root / config["intake_path"])

    project_title = research_map.get("project", {}).get("title", "Untitled")
    questions = research_map.get("questions", [])
    domain = research_map.get("domain", {}).get("name", "Unknown")
    data_files = research_map.get("data", {}).get("files", [])
    q_count = len(questions)
    file_count = len(data_files)
    today = datetime.now().strftime("%Y-%m-%d")

    researcher = "Unknown"
    institution = "Unknown"
    for line in intake.split("\n"):
        stripped = line.strip()
        if stripped.startswith("**Researcher**"):
            researcher = stripped.split(":", 1)[-1].strip().strip("[]")
        elif stripped.startswith("**Institution**"):
            institution = stripped.split(":", 1)[-1].strip().strip("[]")

    dirs = {
        "docs": f"# Research Documentation — {project_title}\n\n> Auto-generated by Research Copilot.\n\n## Project\n- **Researcher**: {researcher}\n- **Institution**: {institution}\n- **Domain**: {domain}\n- **Questions**: {q_count}\n- **Data files**: {file_count}\n- **Started**: {today}",
        "docs/iterations": f"# Research Iterations — {project_title}\n\nEach iteration documents a distinct phase of analysis.",
        "docs/decisions": f"# Methodological Decisions — {project_title}\n\nEvery significant methodological choice is documented here.",
        "docs/dead_ends": f"# Dead Ends — {project_title}\n\nApproaches that were tried and abandoned.",
        "reports": f"# Analysis Reports — {project_title}\n\n> All analysis outputs organized by type and research question.",
        "reports/baseline": f"# Baseline — {project_title}\n\nInitial research map and feasibility assessment.",
        "reports/literature": f"# Literature Review — {project_title}\n\n## Files\n- `literature_corpus.json`\n- `evidence_matrix.md`\n- `gap_analysis.md`",
        "reports/analysis": f"# Analysis Results — {project_title}\n\nResults organized by research question.",
        "reports/figures": f"# Figures — {project_title}\n\nAll generated plots, organized by research question.",
        "reports/tables": f"# Tables — {project_title}\n\nAll generated tables, organized by research question.",
        "reports/dashboards": f"# Dashboards — {project_title}\n\nInteractive summaries.",
        "reports/manuscript": f"# Manuscript — {project_title}\n\nDraft paper sections.",
        "reports/audit": f"# Audit Reports — {project_title}\n\nMulti-dimensional audit reports.",
        "reports/summary": f"# Summary — {project_title}\n\nExecutive summaries and key findings.",
        "data": f"# Data Pipeline — {project_title}\n\nRaw data in `inputs/data/raw/`. This directory contains processed versions.",
        "data/01_ingested": f"# Ingested Data — {project_title}\n\nRaw data cleaned and standardized.",
        "data/02_processed": f"# Processed Data — {project_title}\n\nData merged, filtered, and transformed.",
        "data/03_analytical": f"# Analytical Data — {project_title}\n\nFinal analysis-ready datasets.",
        "scripts": f"# Analysis Scripts — {project_title}\n\nReproducible code for the entire analysis pipeline.",
    }

    created = []
    for dir_path, readme_content in dirs.items():
        full_path = root / dir_path
        full_path.mkdir(parents=True, exist_ok=True)
        readme_path = full_path / "README.md"
        with open(readme_path, "w") as f:
            f.write(readme_content)
        created.append(dir_path)

    manifest = {
        "schema_version": "8.0.0",
        "project": {"title": project_title, "researcher": researcher, "institution": institution, "domain": domain},
        "created": today,
        "last_updated": today,
        "structure": {path: "Created by research_init" for path in dirs.keys()},
        "iterations": [{"id": "001", "type": "initial_setup", "trigger": "research_init agent executed", "date": today, "status": "complete", "summary": "Full directory structure created, intake parsed, data scanned"}],
        "current_phase": "research_init",
        "total_iterations": 1,
        "research_questions": q_count,
        "data_files": file_count,
    }
    manifest_path = root / config.get("manifest", "docs/manifest.json")
    save_json(manifest_path, manifest)

    log_path = root / config.get("research_log", "docs/research_log.md")
    with open(log_path, "w") as f:
        f.write(f"# Research Log — {project_title}\n\n> Chronological record of ALL research activity.\n\n## Log\n\n### {today} — Initial Setup\n- **Agent**: research_init\n- **Action**: Parsed intake, scanned data, created project structure\n- **Questions**: {q_count} research questions identified\n- **Data**: {file_count} files found in inputs/data/raw/\n- **Feasibility**: {research_map.get('feasibility', {}).get('verdict', 'unknown')}\n- **Next step**: Continue through the pipeline\n")

    method_path = root / config.get("methodology", "docs/methodology.md")
    with open(method_path, "w") as f:
        f.write(f"# Methodology — {project_title}\n\n> Methods used and WHY they were chosen.\n\n## Current Methods\nMethods will be selected based on question types during method_route phase.\n")

    changelog_path = root / config.get("changelog", "docs/changelog.md")
    with open(changelog_path, "w") as f:
        f.write(f"# Changelog — {project_title}\n\n> What changed between iterations.\n\n## {today} — Initial Setup\n- Created full directory structure ({len(created)} directories)\n- Parsed {q_count} research questions\n- Scanned {file_count} data files\n")

    registry_path = root / config.get("iteration_registry", "docs/iterations/registry.json")
    save_json(registry_path, {
        "schema_version": "8.0.0",
        "project": project_title,
        "iterations": [{"id": "001", "type": "initial_setup", "trigger": "research_init agent", "date": today, "status": "complete", "summary": "Initial project structure created, intake parsed, data scanned"}],
        "total": 1,
        "current_iteration": "001"
    })

    cache_map = root / config["cache_research_map"]
    if cache_map.exists():
        dest = root / config["research_map"]
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(cache_map, dest)

    print("=" * 60)
    print("DIRECTORY STRUCTURE CREATED")
    print("=" * 60)
    print()
    print(f"  Project: {project_title}")
    print(f"  Directories created: {len(created)}")
    for d in created:
        print(f"    ✓ {d}/")
    print()
    print(f"  Files created:")
    print(f"    ✓ docs/manifest.json")
    print(f"    ✓ docs/research_log.md")
    print(f"    ✓ docs/methodology.md")
    print(f"    ✓ docs/changelog.md")
    print(f"    ✓ docs/iterations/registry.json")
    print(f"    ✓ reports/baseline/research_map.json (copied from cache)")
    print()
    print(f"  Next: Continue with the pipeline agents.")
    print()
