import json
import logging
from typing import Dict, Any, Optional

from research_copilot.assets.schemas.orchestration_schema import SupervisorDecision
from research_copilot.control_plane.planner import PlannerAgent
from research_copilot.intent_router import IntentRouter
from research_copilot.control_plane.prompt_builder import PromptBuilder
from research_copilot.core.state_ledger import ResearchLedger
from research_copilot.core.cognitive_tracker import CognitiveStateTracker
from research_copilot.control_plane.mutation_engine import PlanMutationEngine
from research_copilot.core.memory_synthesizer import MemorySynthesizer

logger = logging.getLogger("research.supervisor")

class SupervisorAgent:
    """Top-level orchestrator that owns conversation, task decomposition, and state transitions."""

    def __init__(self, root, ledger: ResearchLedger, call_llm_fn=None):
        self.root = root
        self.ledger = ledger
        self.cognitive_tracker = CognitiveStateTracker(ledger)
        self.mutation_engine = PlanMutationEngine(ledger)
        if call_llm_fn:
            self.call_llm = call_llm_fn
        else:
            from research_copilot.chat import call_llm
            self.call_llm = call_llm
            
        self.memory_synthesizer = MemorySynthesizer(ledger, self.call_llm)
        self.planner = PlannerAgent(root, self.call_llm)
        self.router = IntentRouter(root)
        self.prompt_builder = PromptBuilder(self.ledger, self.cognitive_tracker)

    def _apply_plan_mutations(self, plan):
        """Applies DAG mutations generated by the DynamicPlanner."""
        if hasattr(plan, "mutations") and plan.mutations:
            for mut in plan.mutations:
                try:
                    if mut.action == "insert":
                        self.mutation_engine.insert_node(mut.node_id, mut.script_path, mut.depends_on)
                    elif mut.action == "remove":
                        self.mutation_engine.remove_node(mut.node_id)
                    elif mut.action == "rewire":
                        self.mutation_engine.rewire_dependency(mut.node_id, mut.depends_on)
                except Exception as e:
                    logger.error(f"Failed to apply DAG mutation {mut.action} on {mut.node_id}: {e}")

    def process_request(self, user_request: str, mode: str = "exploratory") -> SupervisorDecision:
        """Determines the nature of the request and decides on next actions."""
        
        # Build prompt using state-aware builder
        prompt = self.prompt_builder.build_supervisor_prompt(user_request, mode=mode)
        
        raw_response = self.call_llm(prompt)
        
        if raw_response.startswith("```json"):
            raw_response = raw_response[7:]
        if raw_response.endswith("```"):
            raw_response = raw_response[:-3]
            
        try:
            data = json.loads(raw_response.strip())
            
            # Record user turn
            self.ledger.add_conversation_turn("user", user_request)
            
            # Apply any state patches
            if data.get("state_patch"):
                self.ledger.update(**data["state_patch"])
            
            project_state = self.ledger.get()
            
            # Handle different task types
            if data.get("task_type") in ("new_task", "modify", "replan") and not data.get("needs_clarification"):
                plan = self.planner.generate_plan(user_request, project_state)
                self._apply_plan_mutations(plan)
                router_output = self.router.get_minimal_context(user_request)
                
                data["selected_workflow"] = plan.workflow_name
                router_agents = router_output.get("required_agents", [])
                data["selected_agents"] = list(set(data.get("selected_agents", []) + router_agents))
                
                self.ledger.update(
                    active_user_intent=data.get("intent", "none"),
                    current_plan=plan.model_dump()
                )
                
            elif data.get("task_type") == "continuation" and not data.get("needs_clarification"):
                # If there's an interrupt, pop it and resume
                stack = project_state.get("interrupt_stack", [])
                if stack:
                    resumed_state = self.ledger.pop_interrupt()
                    self.ledger.update(
                        active_user_intent=resumed_state.get("active_user_intent", "none"),
                        current_plan=resumed_state.get("current_plan")
                    )
                    data["selected_workflow"] = resumed_state.get("current_plan", {}).get("workflow_name")
                else:
                    # Normal continuation
                    plan = self.planner.generate_plan(user_request, project_state)
                    self._apply_plan_mutations(plan)
                    router_output = self.router.get_minimal_context(user_request)
                    
                    data["selected_workflow"] = plan.workflow_name
                    router_agents = router_output.get("required_agents", [])
                    data["selected_agents"] = list(set(data.get("selected_agents", []) + router_agents))
                    
                    self.ledger.update(
                        active_user_intent=data.get("intent", "none"),
                        current_plan=plan.model_dump()
                    )
                
            elif data.get("task_type") == "branch":
                execution_intent = data.get("execution_intent", {})
                branch_name = execution_intent.get("branch_name_override") or "new_branch"
                
                self.ledger.branch_state(branch_name)
                
                plan = self.planner.generate_plan(user_request, project_state)
                self._apply_plan_mutations(plan)
                self.ledger.update(
                    active_user_intent=data.get("intent", "none"),
                    current_plan=plan.model_dump(),
                    current_branch=branch_name
                )
                data["selected_workflow"] = plan.workflow_name
                
            elif data.get("task_type") == "repair":
                execution_intent = data.get("execution_intent", {})
                rollback_target = execution_intent.get("rollback_target")
                if rollback_target:
                    self.ledger.add_error(f"Rolling back to {rollback_target}")
                
                plan = self.planner.generate_plan(user_request, project_state)
                self._apply_plan_mutations(plan)
                self.ledger.update(current_plan=plan.model_dump())
                data["selected_workflow"] = plan.workflow_name
                
            elif data.get("task_type") == "interruption":
                # Push the old task context
                active_task_summary = self.ledger.get_active_task_summary()
                if active_task_summary:
                    self.ledger.push_interrupt({"active_user_intent": project_state.get("active_user_intent"), "current_plan": project_state.get("current_plan")})
            
            # Record assistant action
            self.ledger.add_conversation_turn("assistant", data.get("next_action", ""))

            # Compress memory if conversation gets too long
            state_data = self.ledger.get()
            turns = state_data.get("conversation_turns", [])
            if len(turns) >= 10:
                self.memory_synthesizer.synthesize_episode(
                    trigger="turn_threshold_reached",
                    recent_turns=turns[-10:],
                    decisions=[data.get("next_action", "")]
                )
                self.memory_synthesizer.roll_semantic_memory()
                # Clear compressed turns, keep last 2 for immediate context
                self.ledger.update(conversation_turns=turns[-2:])
                
            return SupervisorDecision(**data)
        except Exception as e:
            import traceback
            traceback.print_exc()
            logger.error(f"Failed to parse supervisor decision: {e}")
            return SupervisorDecision(
                intent="unknown",
                task_type="interruption",
                urgency="low",
                needs_clarification=True,
                needs_approval=False,
                selected_agents=[],
                next_action="Ask user for clarification",
                state_patch={}
            )
